feign:
  client:
    config:
      default:
        connectTimeOut: 5000 #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        readTimeOut: 5000 #指建立连接后从服务端读取到可用资源所用的时间
        loggerLevel: FULL
logging:
  level:
    com:
      flywolf:
        li:
          sales:
            dou:
              remote: DEBUG