spring:
  cloud:
    gateway:
      routes:
        - id: channel-management  #渠道管理微服务路由
          uri: lb://channel-management # 从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/channel/**

        - id: channel-openapi  #渠道api文档路由
          uri: lb://channel-management
          predicates:
            - Path=/channel-openapi/**
          filters:
            - StripPrefix=1 #过滤掉url第一个前缀

        - id: dou-management  #分销组织管理路由
          uri: lb://dou-management # 从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/dou/**

        - id: dou-openapi  ##分销组织api文档路由
          uri: lb://dou-management #从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/dou-openapi/**
          filters:
            - StripPrefix=1 #过滤掉url第一个前缀

       

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: 渠道管理
        url: /channel-openapi/v3/api-docs
      - name: 分销组织管理
        url: /dou-openapi/v3/api-docs